//
//  VoltraWidgetInitialStates.swift
//
//  Auto-generated by Voltra config plugin.
//  No widget initial states configured.
//

import Foundation

public enum VoltraWidgetInitialStates {
  /// Get the bundled initial state JSON for a widget.
  /// Always returns nil since no initial states are configured.
  public static func getInitialState(for widgetId: String) -> Data? {
    return nil
  }
}