//
  //  VoltraWidgetBundle.swift
  //
  //  Auto-generated by Voltra config plugin.
  //  This file defines which Voltra widgets are available in your app.
  //

  import SwiftUI
  import WidgetKit
  import VoltraWidget

  @main
  struct VoltraWidgetBundle: WidgetBundle {
    var body: some Widget {
      // Live Activity (with Watch/CarPlay support)
      VoltraWidget()

      // Home Screen Widgets
      VoltraWidget_prayer_times()
  VoltraWidget_dua_reflection()
  VoltraWidget_dua_calm()
  VoltraWidget_dua_anxiety()
  VoltraWidget_dua_sadness()
  VoltraWidget_dua_gratitude()
  VoltraWidget_dua_hope()
  VoltraWidget_dua_strength()
  VoltraWidget_dua_guidance()
  VoltraWidget_dua_trust()
  VoltraWidget_dua_peace()
  VoltraWidget_dua_despair()
    }
  }

  // MARK: - Home Screen Widget Definitions

  public struct VoltraWidget_prayer_times: Widget {
private let widgetId = "prayer_times"

public init() {}

public var body: some WidgetConfiguration {
  StaticConfiguration(
    kind: "Voltra_Widget_prayer_times",
    provider: VoltraHomeWidgetProvider(
      widgetId: widgetId,
      initialState: VoltraWidgetInitialStates.getInitialState(for: widgetId)
    )
  ) { entry in
    VoltraHomeWidgetView(entry: entry)
  }
  .configurationDisplayName("Prayer Times")
  .description("Shows prayer times and countdown to next prayer")
  .supportedFamilies([.systemSmall, .systemMedium, .systemLarge])
  .contentMarginsDisabled()
}
}

public struct VoltraWidget_dua_reflection: Widget {
private let widgetId = "dua_reflection"

public init() {}

public var body: some WidgetConfiguration {
  StaticConfiguration(
    kind: "Voltra_Widget_dua_reflection",
    provider: VoltraHomeWidgetProvider(
      widgetId: widgetId,
      initialState: VoltraWidgetInitialStates.getInitialState(for: widgetId)
    )
  ) { entry in
    VoltraHomeWidgetView(entry: entry)
  }
  .configurationDisplayName("Reflection")
  .description("So where are you going?")
  .supportedFamilies([.systemMedium])
  .contentMarginsDisabled()
}
}

public struct VoltraWidget_dua_calm: Widget {
private let widgetId = "dua_calm"

public init() {}

public var body: some WidgetConfiguration {
  StaticConfiguration(
    kind: "Voltra_Widget_dua_calm",
    provider: VoltraHomeWidgetProvider(
      widgetId: widgetId,
      initialState: VoltraWidgetInitialStates.getInitialState(for: widgetId)
    )
  ) { entry in
    VoltraHomeWidgetView(entry: entry)
  }
  .configurationDisplayName("Calm & Ease")
  .description("In the remembrance of Allah do hearts find rest")
  .supportedFamilies([.systemMedium, .systemLarge])
  .contentMarginsDisabled()
}
}

public struct VoltraWidget_dua_anxiety: Widget {
private let widgetId = "dua_anxiety"

public init() {}

public var body: some WidgetConfiguration {
  StaticConfiguration(
    kind: "Voltra_Widget_dua_anxiety",
    provider: VoltraHomeWidgetProvider(
      widgetId: widgetId,
      initialState: VoltraWidgetInitialStates.getInitialState(for: widgetId)
    )
  ) { entry in
    VoltraHomeWidgetView(entry: entry)
  }
  .configurationDisplayName("Anxiety & Fear")
  .description("Allah is sufficient for us")
  .supportedFamilies([.systemMedium, .systemLarge])
  .contentMarginsDisabled()
}
}

public struct VoltraWidget_dua_sadness: Widget {
private let widgetId = "dua_sadness"

public init() {}

public var body: some WidgetConfiguration {
  StaticConfiguration(
    kind: "Voltra_Widget_dua_sadness",
    provider: VoltraHomeWidgetProvider(
      widgetId: widgetId,
      initialState: VoltraWidgetInitialStates.getInitialState(for: widgetId)
    )
  ) { entry in
    VoltraHomeWidgetView(entry: entry)
  }
  .configurationDisplayName("Sadness")
  .description("Do not grieve. Indeed Allah is with us")
  .supportedFamilies([.systemMedium, .systemLarge])
  .contentMarginsDisabled()
}
}

public struct VoltraWidget_dua_gratitude: Widget {
private let widgetId = "dua_gratitude"

public init() {}

public var body: some WidgetConfiguration {
  StaticConfiguration(
    kind: "Voltra_Widget_dua_gratitude",
    provider: VoltraHomeWidgetProvider(
      widgetId: widgetId,
      initialState: VoltraWidgetInitialStates.getInitialState(for: widgetId)
    )
  ) { entry in
    VoltraHomeWidgetView(entry: entry)
  }
  .configurationDisplayName("Gratitude")
  .description("If you are grateful, I will increase you")
  .supportedFamilies([.systemMedium, .systemLarge])
  .contentMarginsDisabled()
}
}

public struct VoltraWidget_dua_hope: Widget {
private let widgetId = "dua_hope"

public init() {}

public var body: some WidgetConfiguration {
  StaticConfiguration(
    kind: "Voltra_Widget_dua_hope",
    provider: VoltraHomeWidgetProvider(
      widgetId: widgetId,
      initialState: VoltraWidgetInitialStates.getInitialState(for: widgetId)
    )
  ) { entry in
    VoltraHomeWidgetView(entry: entry)
  }
  .configurationDisplayName("Hope & Mercy")
  .description("With hardship comes ease")
  .supportedFamilies([.systemMedium, .systemLarge])
  .contentMarginsDisabled()
}
}

public struct VoltraWidget_dua_strength: Widget {
private let widgetId = "dua_strength"

public init() {}

public var body: some WidgetConfiguration {
  StaticConfiguration(
    kind: "Voltra_Widget_dua_strength",
    provider: VoltraHomeWidgetProvider(
      widgetId: widgetId,
      initialState: VoltraWidgetInitialStates.getInitialState(for: widgetId)
    )
  ) { entry in
    VoltraHomeWidgetView(entry: entry)
  }
  .configurationDisplayName("Strength")
  .description("Allah does not burden a soul beyond capacity")
  .supportedFamilies([.systemMedium, .systemLarge])
  .contentMarginsDisabled()
}
}

public struct VoltraWidget_dua_guidance: Widget {
private let widgetId = "dua_guidance"

public init() {}

public var body: some WidgetConfiguration {
  StaticConfiguration(
    kind: "Voltra_Widget_dua_guidance",
    provider: VoltraHomeWidgetProvider(
      widgetId: widgetId,
      initialState: VoltraWidgetInitialStates.getInitialState(for: widgetId)
    )
  ) { entry in
    VoltraHomeWidgetView(entry: entry)
  }
  .configurationDisplayName("Guidance")
  .description("Guide us to the straight path")
  .supportedFamilies([.systemMedium, .systemLarge])
  .contentMarginsDisabled()
}
}

public struct VoltraWidget_dua_trust: Widget {
private let widgetId = "dua_trust"

public init() {}

public var body: some WidgetConfiguration {
  StaticConfiguration(
    kind: "Voltra_Widget_dua_trust",
    provider: VoltraHomeWidgetProvider(
      widgetId: widgetId,
      initialState: VoltraWidgetInitialStates.getInitialState(for: widgetId)
    )
  ) { entry in
    VoltraHomeWidgetView(entry: entry)
  }
  .configurationDisplayName("Trust in Allah")
  .description("Whoever relies upon Allah, He is sufficient")
  .supportedFamilies([.systemMedium, .systemLarge])
  .contentMarginsDisabled()
}
}

public struct VoltraWidget_dua_peace: Widget {
private let widgetId = "dua_peace"

public init() {}

public var body: some WidgetConfiguration {
  StaticConfiguration(
    kind: "Voltra_Widget_dua_peace",
    provider: VoltraHomeWidgetProvider(
      widgetId: widgetId,
      initialState: VoltraWidgetInitialStates.getInitialState(for: widgetId)
    )
  ) { entry in
    VoltraHomeWidgetView(entry: entry)
  }
  .configurationDisplayName("Peace")
  .description("He sends tranquility into the hearts of believers")
  .supportedFamilies([.systemLarge])
  .contentMarginsDisabled()
}
}

public struct VoltraWidget_dua_despair: Widget {
private let widgetId = "dua_despair"

public init() {}

public var body: some WidgetConfiguration {
  StaticConfiguration(
    kind: "Voltra_Widget_dua_despair",
    provider: VoltraHomeWidgetProvider(
      widgetId: widgetId,
      initialState: VoltraWidgetInitialStates.getInitialState(for: widgetId)
    )
  ) { entry in
    VoltraHomeWidgetView(entry: entry)
  }
  .configurationDisplayName("Despair")
  .description("Do not despair of the mercy of Allah")
  .supportedFamilies([.systemLarge])
  .contentMarginsDisabled()
}
}