export interface ArabicLetter {
  id: string;
  letter: string;
  name: string;
  nameArabic: string;
  transliteration: string;
  isolated: string;
  initial: string;
  medial: string;
  final: string;
  pronunciation: string;
  examples: {
    arabic: string;
    transliteration: string;
    meaning: string;
  }[];
}

export const arabicAlphabet: ArabicLetter[] = [
  {
    id: 'alif',
    letter: 'ا',
    name: 'Alif',
    nameArabic: 'أَلِف',
    transliteration: 'a / ā',
    isolated: 'ا',
    initial: 'ا',
    medial: 'ـا',
    final: 'ـا',
    pronunciation: 'Like "a" in "father" or a glottal stop',
    examples: [
      { arabic: 'أَب', transliteration: 'ab', meaning: 'father' },
      { arabic: 'أُم', transliteration: 'umm', meaning: 'mother' },
      { arabic: 'أَرْض', transliteration: 'ard', meaning: 'earth' },
    ],
  },
  {
    id: 'ba',
    letter: 'ب',
    name: 'Ba',
    nameArabic: 'بَاء',
    transliteration: 'b',
    isolated: 'ب',
    initial: 'بـ',
    medial: 'ـبـ',
    final: 'ـب',
    pronunciation: 'Like "b" in "boy"',
    examples: [
      { arabic: 'بَيْت', transliteration: 'bayt', meaning: 'house' },
      { arabic: 'بَاب', transliteration: 'bāb', meaning: 'door' },
      { arabic: 'كِتَاب', transliteration: 'kitāb', meaning: 'book' },
    ],
  },
  {
    id: 'ta',
    letter: 'ت',
    name: 'Ta',
    nameArabic: 'تَاء',
    transliteration: 't',
    isolated: 'ت',
    initial: 'تـ',
    medial: 'ـتـ',
    final: 'ـت',
    pronunciation: 'Like "t" in "top"',
    examples: [
      { arabic: 'تَمْر', transliteration: 'tamr', meaning: 'dates' },
      { arabic: 'تِين', transliteration: 'tīn', meaning: 'figs' },
      { arabic: 'بِنْت', transliteration: 'bint', meaning: 'girl' },
    ],
  },
  {
    id: 'tha',
    letter: 'ث',
    name: 'Tha',
    nameArabic: 'ثَاء',
    transliteration: 'th',
    isolated: 'ث',
    initial: 'ثـ',
    medial: 'ـثـ',
    final: 'ـث',
    pronunciation: 'Like "th" in "think"',
    examples: [
      { arabic: 'ثَلَاثَة', transliteration: 'thalātha', meaning: 'three' },
      { arabic: 'ثَوْب', transliteration: 'thawb', meaning: 'garment' },
      { arabic: 'حَدِيث', transliteration: 'hadīth', meaning: 'narration' },
    ],
  },
  {
    id: 'jim',
    letter: 'ج',
    name: 'Jim',
    nameArabic: 'جِيم',
    transliteration: 'j',
    isolated: 'ج',
    initial: 'جـ',
    medial: 'ـجـ',
    final: 'ـج',
    pronunciation: 'Like "j" in "jump"',
    examples: [
      { arabic: 'جَنَّة', transliteration: 'jannah', meaning: 'paradise' },
      { arabic: 'جَمَل', transliteration: 'jamal', meaning: 'camel' },
      { arabic: 'حَج', transliteration: 'hajj', meaning: 'pilgrimage' },
    ],
  },
  {
    id: 'ha',
    letter: 'ح',
    name: 'Ha',
    nameArabic: 'حَاء',
    transliteration: 'ḥ',
    isolated: 'ح',
    initial: 'حـ',
    medial: 'ـحـ',
    final: 'ـح',
    pronunciation: 'A breathy "h" from the throat',
    examples: [
      { arabic: 'حَمْد', transliteration: 'ḥamd', meaning: 'praise' },
      { arabic: 'حَق', transliteration: 'ḥaqq', meaning: 'truth' },
      { arabic: 'رَحْمَة', transliteration: 'raḥmah', meaning: 'mercy' },
    ],
  },
  {
    id: 'kha',
    letter: 'خ',
    name: 'Kha',
    nameArabic: 'خَاء',
    transliteration: 'kh',
    isolated: 'خ',
    initial: 'خـ',
    medial: 'ـخـ',
    final: 'ـخ',
    pronunciation: 'Like "ch" in Scottish "loch"',
    examples: [
      { arabic: 'خَيْر', transliteration: 'khayr', meaning: 'good' },
      { arabic: 'خُبْز', transliteration: 'khubz', meaning: 'bread' },
      { arabic: 'أَخ', transliteration: 'akh', meaning: 'brother' },
    ],
  },
  {
    id: 'dal',
    letter: 'د',
    name: 'Dal',
    nameArabic: 'دَال',
    transliteration: 'd',
    isolated: 'د',
    initial: 'د',
    medial: 'ـد',
    final: 'ـد',
    pronunciation: 'Like "d" in "dog"',
    examples: [
      { arabic: 'دِين', transliteration: 'dīn', meaning: 'religion' },
      { arabic: 'دَار', transliteration: 'dār', meaning: 'home' },
      { arabic: 'وَلَد', transliteration: 'walad', meaning: 'boy' },
    ],
  },
  {
    id: 'dhal',
    letter: 'ذ',
    name: 'Dhal',
    nameArabic: 'ذَال',
    transliteration: 'dh',
    isolated: 'ذ',
    initial: 'ذ',
    medial: 'ـذ',
    final: 'ـذ',
    pronunciation: 'Like "th" in "this"',
    examples: [
      { arabic: 'ذِكْر', transliteration: 'dhikr', meaning: 'remembrance' },
      { arabic: 'ذَهَب', transliteration: 'dhahab', meaning: 'gold' },
      { arabic: 'هَذَا', transliteration: 'hādhā', meaning: 'this' },
    ],
  },
  {
    id: 'ra',
    letter: 'ر',
    name: 'Ra',
    nameArabic: 'رَاء',
    transliteration: 'r',
    isolated: 'ر',
    initial: 'ر',
    medial: 'ـر',
    final: 'ـر',
    pronunciation: 'Rolled "r" like in Spanish',
    examples: [
      { arabic: 'رَبّ', transliteration: 'rabb', meaning: 'lord' },
      { arabic: 'رَحْمَن', transliteration: 'raḥmān', meaning: 'most merciful' },
      { arabic: 'نَار', transliteration: 'nār', meaning: 'fire' },
    ],
  },
  {
    id: 'zay',
    letter: 'ز',
    name: 'Zay',
    nameArabic: 'زَاي',
    transliteration: 'z',
    isolated: 'ز',
    initial: 'ز',
    medial: 'ـز',
    final: 'ـز',
    pronunciation: 'Like "z" in "zebra"',
    examples: [
      { arabic: 'زَكَاة', transliteration: 'zakāh', meaning: 'charity' },
      { arabic: 'زَيْت', transliteration: 'zayt', meaning: 'oil' },
      { arabic: 'عَزِيز', transliteration: 'ʿazīz', meaning: 'mighty' },
    ],
  },
  {
    id: 'sin',
    letter: 'س',
    name: 'Sin',
    nameArabic: 'سِين',
    transliteration: 's',
    isolated: 'س',
    initial: 'سـ',
    medial: 'ـسـ',
    final: 'ـس',
    pronunciation: 'Like "s" in "sun"',
    examples: [
      { arabic: 'سَلَام', transliteration: 'salām', meaning: 'peace' },
      { arabic: 'سَمَاء', transliteration: 'samāʾ', meaning: 'sky' },
      { arabic: 'نَفْس', transliteration: 'nafs', meaning: 'soul' },
    ],
  },
  {
    id: 'shin',
    letter: 'ش',
    name: 'Shin',
    nameArabic: 'شِين',
    transliteration: 'sh',
    isolated: 'ش',
    initial: 'شـ',
    medial: 'ـشـ',
    final: 'ـش',
    pronunciation: 'Like "sh" in "ship"',
    examples: [
      { arabic: 'شَمْس', transliteration: 'shams', meaning: 'sun' },
      { arabic: 'شُكْر', transliteration: 'shukr', meaning: 'gratitude' },
      { arabic: 'عَرْش', transliteration: 'ʿarsh', meaning: 'throne' },
    ],
  },
  {
    id: 'sad',
    letter: 'ص',
    name: 'Sad',
    nameArabic: 'صَاد',
    transliteration: 'ṣ',
    isolated: 'ص',
    initial: 'صـ',
    medial: 'ـصـ',
    final: 'ـص',
    pronunciation: 'Emphatic "s" - tongue touches roof of mouth',
    examples: [
      { arabic: 'صَلَاة', transliteration: 'ṣalāh', meaning: 'prayer' },
      { arabic: 'صَبْر', transliteration: 'ṣabr', meaning: 'patience' },
      { arabic: 'صِرَاط', transliteration: 'ṣirāṭ', meaning: 'path' },
    ],
  },
  {
    id: 'dad',
    letter: 'ض',
    name: 'Dad',
    nameArabic: 'ضَاد',
    transliteration: 'ḍ',
    isolated: 'ض',
    initial: 'ضـ',
    medial: 'ـضـ',
    final: 'ـض',
    pronunciation: 'Emphatic "d" - unique to Arabic',
    examples: [
      { arabic: 'ضَوْء', transliteration: 'ḍawʾ', meaning: 'light' },
      { arabic: 'أَرْض', transliteration: 'arḍ', meaning: 'earth' },
      { arabic: 'رَمَضَان', transliteration: 'ramaḍān', meaning: 'Ramadan' },
    ],
  },
  {
    id: 'ta-emphatic',
    letter: 'ط',
    name: 'Ta (emphatic)',
    nameArabic: 'طَاء',
    transliteration: 'ṭ',
    isolated: 'ط',
    initial: 'طـ',
    medial: 'ـطـ',
    final: 'ـط',
    pronunciation: 'Emphatic "t" - deeper, heavier sound',
    examples: [
      { arabic: 'طَهَارَة', transliteration: 'ṭahārah', meaning: 'purity' },
      { arabic: 'طَيِّب', transliteration: 'ṭayyib', meaning: 'good/pure' },
      { arabic: 'صِرَاط', transliteration: 'ṣirāṭ', meaning: 'path' },
    ],
  },
  {
    id: 'dha-emphatic',
    letter: 'ظ',
    name: 'Dha (emphatic)',
    nameArabic: 'ظَاء',
    transliteration: 'ẓ',
    isolated: 'ظ',
    initial: 'ظـ',
    medial: 'ـظـ',
    final: 'ـظ',
    pronunciation: 'Emphatic "th" as in "this"',
    examples: [
      { arabic: 'ظُلْم', transliteration: 'ẓulm', meaning: 'oppression' },
      { arabic: 'عَظِيم', transliteration: 'ʿaẓīm', meaning: 'great' },
      { arabic: 'حَافِظ', transliteration: 'ḥāfiẓ', meaning: 'guardian' },
    ],
  },
  {
    id: 'ayn',
    letter: 'ع',
    name: 'Ayn',
    nameArabic: 'عَيْن',
    transliteration: 'ʿ',
    isolated: 'ع',
    initial: 'عـ',
    medial: 'ـعـ',
    final: 'ـع',
    pronunciation: 'Deep guttural sound from throat',
    examples: [
      { arabic: 'عِلْم', transliteration: 'ʿilm', meaning: 'knowledge' },
      { arabic: 'عَبْد', transliteration: 'ʿabd', meaning: 'servant' },
      { arabic: 'سَمِيع', transliteration: 'samīʿ', meaning: 'all-hearing' },
    ],
  },
  {
    id: 'ghayn',
    letter: 'غ',
    name: 'Ghayn',
    nameArabic: 'غَيْن',
    transliteration: 'gh',
    isolated: 'غ',
    initial: 'غـ',
    medial: 'ـغـ',
    final: 'ـغ',
    pronunciation: 'Like French "r" or gargling sound',
    examples: [
      { arabic: 'غَفُور', transliteration: 'ghafūr', meaning: 'forgiving' },
      { arabic: 'غَيْب', transliteration: 'ghayb', meaning: 'unseen' },
      { arabic: 'بَلَغ', transliteration: 'balagha', meaning: 'to reach' },
    ],
  },
  {
    id: 'fa',
    letter: 'ف',
    name: 'Fa',
    nameArabic: 'فَاء',
    transliteration: 'f',
    isolated: 'ف',
    initial: 'فـ',
    medial: 'ـفـ',
    final: 'ـف',
    pronunciation: 'Like "f" in "far"',
    examples: [
      { arabic: 'فَجْر', transliteration: 'fajr', meaning: 'dawn' },
      { arabic: 'فِرْدَوْس', transliteration: 'firdaws', meaning: 'paradise' },
      { arabic: 'كَافِر', transliteration: 'kāfir', meaning: 'disbeliever' },
    ],
  },
  {
    id: 'qaf',
    letter: 'ق',
    name: 'Qaf',
    nameArabic: 'قَاف',
    transliteration: 'q',
    isolated: 'ق',
    initial: 'قـ',
    medial: 'ـقـ',
    final: 'ـق',
    pronunciation: 'Deep "k" from back of throat',
    examples: [
      { arabic: 'قُرْآن', transliteration: 'qurʾān', meaning: 'Quran' },
      { arabic: 'قَلْب', transliteration: 'qalb', meaning: 'heart' },
      { arabic: 'حَق', transliteration: 'ḥaqq', meaning: 'truth' },
    ],
  },
  {
    id: 'kaf',
    letter: 'ك',
    name: 'Kaf',
    nameArabic: 'كَاف',
    transliteration: 'k',
    isolated: 'ك',
    initial: 'كـ',
    medial: 'ـكـ',
    final: 'ـك',
    pronunciation: 'Like "k" in "king"',
    examples: [
      { arabic: 'كِتَاب', transliteration: 'kitāb', meaning: 'book' },
      { arabic: 'كَرِيم', transliteration: 'karīm', meaning: 'generous' },
      { arabic: 'مَلِك', transliteration: 'malik', meaning: 'king' },
    ],
  },
  {
    id: 'lam',
    letter: 'ل',
    name: 'Lam',
    nameArabic: 'لَام',
    transliteration: 'l',
    isolated: 'ل',
    initial: 'لـ',
    medial: 'ـلـ',
    final: 'ـل',
    pronunciation: 'Like "l" in "light"',
    examples: [
      { arabic: 'لَيْل', transliteration: 'layl', meaning: 'night' },
      { arabic: 'الله', transliteration: 'Allāh', meaning: 'God' },
      { arabic: 'جَمَال', transliteration: 'jamāl', meaning: 'beauty' },
    ],
  },
  {
    id: 'mim',
    letter: 'م',
    name: 'Mim',
    nameArabic: 'مِيم',
    transliteration: 'm',
    isolated: 'م',
    initial: 'مـ',
    medial: 'ـمـ',
    final: 'ـم',
    pronunciation: 'Like "m" in "moon"',
    examples: [
      { arabic: 'مُسْلِم', transliteration: 'muslim', meaning: 'Muslim' },
      { arabic: 'مَاء', transliteration: 'māʾ', meaning: 'water' },
      { arabic: 'سَلَام', transliteration: 'salām', meaning: 'peace' },
    ],
  },
  {
    id: 'nun',
    letter: 'ن',
    name: 'Nun',
    nameArabic: 'نُون',
    transliteration: 'n',
    isolated: 'ن',
    initial: 'نـ',
    medial: 'ـنـ',
    final: 'ـن',
    pronunciation: 'Like "n" in "noon"',
    examples: [
      { arabic: 'نُور', transliteration: 'nūr', meaning: 'light' },
      { arabic: 'نَبِي', transliteration: 'nabī', meaning: 'prophet' },
      { arabic: 'إِيمَان', transliteration: 'īmān', meaning: 'faith' },
    ],
  },
  {
    id: 'ha-light',
    letter: 'ه',
    name: 'Ha',
    nameArabic: 'هَاء',
    transliteration: 'h',
    isolated: 'ه',
    initial: 'هـ',
    medial: 'ـهـ',
    final: 'ـه',
    pronunciation: 'Like "h" in "he" (lighter than ح)',
    examples: [
      { arabic: 'هُدَى', transliteration: 'hudā', meaning: 'guidance' },
      { arabic: 'هَذَا', transliteration: 'hādhā', meaning: 'this' },
      { arabic: 'الله', transliteration: 'Allāh', meaning: 'God' },
    ],
  },
  {
    id: 'waw',
    letter: 'و',
    name: 'Waw',
    nameArabic: 'وَاو',
    transliteration: 'w / ū',
    isolated: 'و',
    initial: 'و',
    medial: 'ـو',
    final: 'ـو',
    pronunciation: 'Like "w" in "water" or "oo" in "food"',
    examples: [
      { arabic: 'وَاحِد', transliteration: 'wāḥid', meaning: 'one' },
      { arabic: 'نُور', transliteration: 'nūr', meaning: 'light' },
      { arabic: 'يَوْم', transliteration: 'yawm', meaning: 'day' },
    ],
  },
  {
    id: 'ya',
    letter: 'ي',
    name: 'Ya',
    nameArabic: 'يَاء',
    transliteration: 'y / ī',
    isolated: 'ي',
    initial: 'يـ',
    medial: 'ـيـ',
    final: 'ـي',
    pronunciation: 'Like "y" in "yes" or "ee" in "see"',
    examples: [
      { arabic: 'يَوْم', transliteration: 'yawm', meaning: 'day' },
      { arabic: 'دِين', transliteration: 'dīn', meaning: 'religion' },
      { arabic: 'نَبِي', transliteration: 'nabī', meaning: 'prophet' },
    ],
  },
];

export const getLetterById = (id: string): ArabicLetter | undefined => {
  return arabicAlphabet.find((letter) => letter.id === id);
};

export const getTotalLetters = (): number => {
  return arabicAlphabet.length;
};
