import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    // paddingTop: 60,
    paddingBottom: 40,
    paddingHorizontal: 16,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  loadingCard: {
    padding: 40,
    borderRadius: 40,
    overflow: 'hidden',
    borderCurve: 'continuous',
    alignItems: 'center',
    borderWidth: 1,
    minWidth: 200,
  },
  loadingSpinner: {
    marginBottom: 16,
  },
  loadingText: {
    fontFamily: 'Tajawal-Medium',
    fontSize: 16,
    textAlign: 'center',
  },
  header: {
    alignItems: 'center',
    marginBottom: 32,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  headerTitle: {
    fontSize: 28,
    fontFamily: 'Tajawal-Bold',
    marginBottom: 4,
  },
  headerDate: {
    fontSize: 16,
    fontFamily: 'Tajawal-Light',
  },
  heroCard: {
    marginBottom: 40,
    borderRadius: 28,
    borderCurve: 'continuous',
    overflow: 'hidden',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  heroBlur: {
    padding: 32,
  },
  heroContent: {
    alignItems: 'center',
  },
  heroLabel: {
    fontSize: 14,
    fontFamily: 'Tajawal-Bold',
    marginBottom: 16,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  heroMain: {
    alignItems: 'center',
    marginBottom: 12,
  },
  heroPrayerName: {
    fontSize: 36,
    fontFamily: 'Tajawal-Bold',
    marginBottom: 8,
    letterSpacing: -1,
  },
  heroPrayerTime: {
    fontSize: 28,
    fontFamily: 'Tajawal-Bold',
    marginBottom: 20,
    fontVariant: ['tabular-nums'],
  },
  countdownContainer: {
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 36,
    borderCurve: 'continuous',
  },
  countdownLabel: {
    fontSize: 12,
    fontFamily: 'Tajawal-Bold',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  countdown: {
    fontSize: 20,
    fontFamily: 'Tajawal-Bold',
    fontVariant: ['tabular-nums'],
  },
  gridContainer: {
    gap: 16,
  },
  gridTitle: {
    fontSize: 22,
    fontFamily: 'Tajawal-Bold',
    marginBottom: 20,
    letterSpacing: -0.3,
  },
  prayerGrid: {
    gap: 16,
  },
  prayerCard: {
    borderRadius: 20,
    borderCurve: 'continuous',
    overflow: 'hidden',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  },
  prayerCardContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
  },
  prayerName: {
    fontSize: 18,
    fontFamily: 'Tajawal-Medium',
  },
  prayerTime: {
    fontSize: 18,
    fontFamily: 'Tajawal-Light',
    fontVariant: ['tabular-nums'],
  },
  overlayContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  overlayCard: {
    width: '100%',
    maxWidth: 400,
    borderRadius: 40,
    overflow: 'hidden',
    borderCurve: 'continuous',
  },
  overlayHeader: {
    alignItems: 'center',
    paddingTop: 40,
    paddingHorizontal: 32,
    paddingBottom: 24,
    borderBottomWidth: 4,
  },
  overlayTitle: {
    fontSize: 40,
    fontFamily: 'Tajawal-Bold',
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  overlayTime: {
    fontSize: 18,
    fontFamily: 'Tajawal-Medium',
    fontVariant: ['tabular-nums'],
  },
  overlayRakatsContainer: {
    paddingHorizontal: 32,
    paddingVertical: 24,
  },
  overlayRakatsTitle: {
    fontSize: 14,
    fontFamily: 'Tajawal-Bold',
    marginBottom: 16,
    letterSpacing: 1,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  overlayRakats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  rakatItem: {
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 16,
    borderCurve: 'continuous',
    minWidth: 80,
  },
  rakatNumber: {
    fontSize: 24,
    fontFamily: 'Tajawal-Bold',
    marginBottom: 4,
  },
  rakatLabel: {
    fontSize: 12,
    fontFamily: 'Tajawal-Bold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  overlayDescContainer: {
    paddingHorizontal: 32,
    paddingVertical: 24,
    borderTopWidth: 4,
  },
  overlayDesc: {
    fontSize: 18,
    lineHeight: 22,
    fontFamily: 'Tajawal-Regular',
    textAlign: 'justify',
  },
  overlayClose: {
    margin: 32,
    marginTop: 24,
    borderRadius: 28,
    borderCurve: 'continuous',
    overflow: 'hidden',
  },
  overlayCloseBlur: {
    paddingVertical: 16,
    paddingHorizontal: 32,
    alignItems: 'center',
  },
  overlayCloseText: {
    fontSize: 16,
    fontFamily: 'Tajawal-Bold',
  },
});
